version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    env_file:
    - ~/.secrets/phpapp.env
    ports:
      - 3306:3306
  nginx:
    image: nginx
    restart: always
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.certs:/etc/certs
    ports:
     - "443:443"
    healthcheck:
      test: "curl https://localhost"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
