version: '3.1'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ..:/etc/certs
    ports:
     - "443:443"
  mariadb:
    image: mariadb
    restart: always
    volumes:
     - ./data:/var/lib/mysql
    env_file:
      - ../phpapp.env
    ports:
      - 3306:3306
